[infinit]
pL = 0.3
initial_conf = "gromacs_input/conf.g96"
lamres = 0.001
skip = 0.0
steps_per_iter = [
    50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
    50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
    50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
]

[runner]
workers = 4
wmdrun = [
    "gmx_mpi mdrun -ntomp 5 -pinstride 1 -pinoffset 0  -pin on -notunepme -nb gpu -bonded gpu -pme gpu",
    "gmx_mpi mdrun -ntomp 5 -pinstride 1 -pinoffset 5  -pin on -notunepme -nb gpu -bonded gpu -pme gpu",
    "gmx_mpi mdrun -ntomp 5 -pinstride 1 -pinoffset 10 -pin on -notunepme -nb gpu -bonded gpu -pme gpu",
    "gmx_mpi mdrun -ntomp 5 -pinstride 1 -pinoffset 15 -pin on -notunepme -nb gpu -bonded gpu -pme gpu",
]

[simulation]
interfaces = [-1.8, 2.0]

steps = 100000
seed = 0
load_dir = "load"
shooting_moves = [
    "sh", "sh", "wf", "wf",
]

[simulation.tis_set]
maxlength = 2000000
allowmaxlength = false
zero_momentum = true
n_jumps = 1

[engine]
class = "gromacs"
engine = "gmx"
timestep = 0.002
gmx_format = "g96"
input_path = "gromacs_input"
gmx = "gmx_mpi"
subcycles = 1000
temperature = 300.00
maxwarn = 1

[orderparameter]
class = "PositionX"
module = "orderp.py"
config = "gromacs_input/conf.gro"

[output]
data_dir = "./"
screen = 1
pattern = 0
delete_old = true
keep_maxop_trajs=true
keep_traj_fnames = [
    ".xtc",
]
